quarkus.datasource.db-kind=mysql
quarkus.datasource.username=app_user
quarkus.datasource.password=app_password
quarkus.datasource.jdbc.url=jdbc:mysql://127.0.0.1:3307/resource_planning

quarkus.hibernate-orm.database.generation=none
quarkus.flyway.migrate-at-start=true
quarkus.hibernate-orm.log.sql=true

quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger

quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:5173
quarkus.http.cors.methods=GET,PATCH,POST,DELETE,OPTIONS
quarkus.http.cors.headers=Content-Type,Accept