quarkus.datasource.db-kind=mysql
quarkus.datasource.username=app_user
quarkus.datasource.password=app_password
quarkus.datasource.jdbc.url=jdbc:mysql://127.0.0.1:3307/resource_planning

quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true

quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger